-- =====================================================================
-- V6 : Sous-comptes OHADA détaillés (4 chiffres)
--      ON CONFLICT (numero) DO NOTHING — sans effet si déjà présent
-- =====================================================================
INSERT INTO comptes_ohada (numero, libelle, type, classe) VALUES

    -- ══════════════════════════════════════════════
    -- CLASSE 1 : Ressources durables
    -- ══════════════════════════════════════════════
    ('1011', 'Capital souscrit appelé, versé',                  'PASSIF', 1),
    ('1012', 'Capital souscrit appelé, non versé',              'PASSIF', 1),
    ('1013', 'Capital souscrit non appelé',                     'PASSIF', 1),
    ('1061', 'Réserve légale',                                   'PASSIF', 1),
    ('1062', 'Réserve statutaire',                               'PASSIF', 1),
    ('1063', 'Réserves libres',                                  'PASSIF', 1),
    ('1068', 'Autres réserves',                                  'PASSIF', 1),
    ('1621', 'Emprunts auprès des banques locales',              'PASSIF', 1),
    ('1622', 'Emprunts auprès des organismes financiers',        'PASSIF', 1),
    ('1651', 'Dépôts reçus',                                     'PASSIF', 1),
    ('1652', 'Cautionnements reçus',                             'PASSIF', 1),

    -- ══════════════════════════════════════════════
    -- CLASSE 2 : Actif immobilisé
    -- ══════════════════════════════════════════════
    ('2111', 'Frais de constitution',                            'ACTIF', 2),
    ('2112', 'Frais de premier établissement',                   'ACTIF', 2),
    ('2113', 'Frais de prospection',                             'ACTIF', 2),
    ('2121', 'Brevets',                                          'ACTIF', 2),
    ('2122', 'Licences et concessions',                          'ACTIF', 2),
    ('2131', 'Logiciels acquis',                                 'ACTIF', 2),
    ('2132', 'Sites internet',                                   'ACTIF', 2),
    ('2211', 'Terrains nus',                                     'ACTIF', 2),
    ('2212', 'Terrains aménagés',                                'ACTIF', 2),
    ('2311', 'Bâtiments à usage commercial',                     'ACTIF', 2),
    ('2312', 'Bâtiments à usage industriel',                     'ACTIF', 2),
    ('2313', 'Bâtiments administratifs',                         'ACTIF', 2),
    ('2411', 'Matériel et outillage industriel',                 'ACTIF', 2),
    ('2412', 'Outillage',                                        'ACTIF', 2),
    ('2441', 'Matériel informatique',                            'ACTIF', 2),
    ('2442', 'Matériel de bureau',                               'ACTIF', 2),
    ('2443', 'Mobilier de bureau',                               'ACTIF', 2),
    ('2451', 'Automobiles',                                      'ACTIF', 2),
    ('2452', 'Camions et véhicules utilitaires',                 'ACTIF', 2),
    ('2456', 'Motocycles',                                       'ACTIF', 2),
    ('2811', 'Amort. frais de développement',                    'ACTIF', 2),
    ('2821', 'Amort. brevets et licences',                       'ACTIF', 2),
    ('2831', 'Amort. logiciels',                                 'ACTIF', 2),
    ('2841', 'Amort. matériel et outillage',                     'ACTIF', 2),
    ('2844', 'Amort. matériel informatique',                     'ACTIF', 2),
    ('2845', 'Amort. matériel de transport',                     'ACTIF', 2),

    -- ══════════════════════════════════════════════
    -- CLASSE 3 : Stocks
    -- ══════════════════════════════════════════════
    ('3111', 'Marchandises — stock initial',                     'ACTIF', 3),
    ('3211', 'Matières premières',                               'ACTIF', 3),
    ('3212', 'Fournitures consommables',                         'ACTIF', 3),
    ('3213', 'Fournitures de bureau',                            'ACTIF', 3),
    ('3281', 'Emballages récupérables',                          'ACTIF', 3),

    -- ══════════════════════════════════════════════
    -- CLASSE 4 : Comptes de tiers
    -- ══════════════════════════════════════════════
    ('4011', 'Fournisseurs locaux — dettes en compte',           'PASSIF', 4),
    ('4012', 'Fournisseurs étrangers — dettes en compte',        'PASSIF', 4),
    ('4031', 'Fournisseurs effets à payer',                      'PASSIF', 4),
    ('4081', 'Fournisseurs — factures non parvenues',            'PASSIF', 4),
    ('4091', 'Fournisseurs débiteurs — avances',                 'ACTIF',  4),
    ('4111', 'Clients locaux',                                   'ACTIF',  4),
    ('4112', 'Clients internationaux',                           'ACTIF',  4),
    ('4161', 'Créances clients litigieuses',                     'ACTIF',  4),
    ('4162', 'Créances clients douteuses',                       'ACTIF',  4),
    ('4181', 'Clients — produits non encore facturés',           'ACTIF',  4),
    ('4211', 'Personnel — avances sur salaires',                 'ACTIF',  4),
    ('4212', 'Personnel — prêts accordés',                       'ACTIF',  4),
    ('4221', 'Personnel — appointements et salaires',            'PASSIF', 4),
    ('4222', 'Personnel — congés à payer',                       'PASSIF', 4),
    ('4226', 'Personnel — participation aux bénéfices',          'PASSIF', 4),
    ('4311', 'INSS — cotisations patronales',                    'PASSIF', 4),
    ('4312', 'INSS — cotisations salariales',                    'PASSIF', 4),
    ('4411', 'État — impôt sur les bénéfices',                   'PASSIF', 4),
    ('4412', 'État — acomptes versés sur IBP',                   'ACTIF',  4),
    ('4431', 'TVA facturée',                                     'PASSIF', 4),
    ('4451', 'TVA récupérable sur achats',                       'ACTIF',  4),
    ('4452', 'TVA récupérable sur immobilisations',              'ACTIF',  4),
    ('4471', 'État — IPR (impôt professionnel retenu)',          'PASSIF', 4),
    ('4472', 'État — retenues à la source diverses',             'PASSIF', 4),
    ('4711', 'Débiteurs divers',                                  'ACTIF',  4),
    ('4712', 'Créditeurs divers',                                 'PASSIF', 4),
    ('4911', 'Dépréciations créances clients',                   'ACTIF',  4),

    -- ══════════════════════════════════════════════
    -- CLASSE 5 : Trésorerie
    -- ══════════════════════════════════════════════
    ('5211', 'Banque locale — compte courant CDF',               'ACTIF', 5),
    ('5212', 'Banque locale — compte courant USD',               'ACTIF', 5),
    ('5213', 'Banque locale — compte courant EUR',               'ACTIF', 5),
    ('5221', 'Banque étrangère — compte courant',                'ACTIF', 5),
    ('5311', 'Établissements de microfinance — compte CDF',      'ACTIF', 5),
    ('5312', 'Établissements de microfinance — compte USD',      'ACTIF', 5),
    ('5711', 'Caisse CDF',                                       'ACTIF', 5),
    ('5712', 'Caisse USD',                                       'ACTIF', 5),
    ('5713', 'Caisse EUR',                                       'ACTIF', 5),
    ('5714', 'Caisse petite monnaie',                            'ACTIF', 5),
    ('5811', 'Virements internes',                               'ACTIF', 5),

    -- ══════════════════════════════════════════════
    -- CLASSE 6 : Charges des activités ordinaires
    -- ══════════════════════════════════════════════
    ('6011', 'Achats de marchandises',                           'CHARGE', 6),
    ('6012', 'Variation de stocks de marchandises',              'CHARGE', 6),
    ('6021', 'Achats de matières premières',                     'CHARGE', 6),
    ('6022', 'Variation de stocks de matières premières',        'CHARGE', 6),
    ('6031', 'Fournitures de bureau',                            'CHARGE', 6),
    ('6032', 'Fournitures informatiques',                        'CHARGE', 6),
    ('6033', 'Fournitures d''entretien',                         'CHARGE', 6),
    ('6081', 'Achats d''emballages',                             'CHARGE', 6),
    ('6111', 'Transport de personnel',                           'CHARGE', 6),
    ('6112', 'Transport de marchandises',                        'CHARGE', 6),
    ('6121', 'Fret et livraisons',                               'CHARGE', 6),
    ('6211', 'Loyers de bureaux',                                'CHARGE', 6),
    ('6212', 'Loyers de terrains et bâtiments',                  'CHARGE', 6),
    ('6213', 'Loyers de matériels et véhicules',                 'CHARGE', 6),
    ('6221', 'Entretien et réparations — bâtiments',             'CHARGE', 6),
    ('6222', 'Entretien et réparations — matériels',             'CHARGE', 6),
    ('6223', 'Entretien et réparations — informatique',          'CHARGE', 6),
    ('6231', 'Primes d''assurance dommages',                     'CHARGE', 6),
    ('6232', 'Primes d''assurance vie personnel',                'CHARGE', 6),
    ('6241', 'Études et recherches externes',                    'CHARGE', 6),
    ('6251', 'Documentation générale',                           'CHARGE', 6),
    ('6311', 'Honoraires conseil juridique',                     'CHARGE', 6),
    ('6312', 'Honoraires experts-comptables',                    'CHARGE', 6),
    ('6313', 'Honoraires consultants',                           'CHARGE', 6),
    ('6321', 'Charges de formation',                             'CHARGE', 6),
    ('6322', 'Frais de recrutement',                             'CHARGE', 6),
    ('6323', 'Frais de déplacement et missions',                 'CHARGE', 6),
    ('6324', 'Frais de représentation',                          'CHARGE', 6),
    ('6351', 'Frais postaux',                                    'CHARGE', 6),
    ('6352', 'Frais de télécommunication',                       'CHARGE', 6),
    ('6353', 'Abonnements internet',                             'CHARGE', 6),
    ('6361', 'Frais d''actes et de contentieux',                 'CHARGE', 6),
    ('6371', 'Frais d''hygiène, nettoyage et sécurité',          'CHARGE', 6),
    ('6381', 'Publicité et communication',                       'CHARGE', 6),
    ('6382', 'Relations publiques',                              'CHARGE', 6),
    ('6383', 'Eau et électricité',                               'CHARGE', 6),
    ('6384', 'Carburant et lubrifiants',                         'CHARGE', 6),
    ('6385', 'Gardiennage et sécurité',                          'CHARGE', 6),
    ('6386', 'Charges informatiques (cloud, licences)',          'CHARGE', 6),
    ('6411', 'Impôts fonciers',                                  'CHARGE', 6),
    ('6412', 'Patente et licences commerciales',                 'CHARGE', 6),
    ('6413', 'Taxe sur les véhicules',                           'CHARGE', 6),
    ('6414', 'Taxe rémunératoire',                               'CHARGE', 6),
    ('6451', 'Taxe sur le chiffre d''affaires',                  'CHARGE', 6),
    ('6461', 'Droits d''enregistrement',                         'CHARGE', 6),
    ('6471', 'Pénalités et amendes fiscales',                    'CHARGE', 6),
    ('6511', 'Pertes sur créances irrécouvrables',               'CHARGE', 6),
    ('6521', 'Charges sur exercices antérieurs',                 'CHARGE', 6),
    ('6541', 'Dons et libéralités',                              'CHARGE', 6),
    ('6591', 'Autres charges d''exploitation diverses',          'CHARGE', 6),
    ('6611', 'Appointements et salaires',                        'CHARGE', 6),
    ('6612', 'Primes et gratifications',                         'CHARGE', 6),
    ('6613', 'Congés payés',                                     'CHARGE', 6),
    ('6614', 'Avantages en nature',                              'CHARGE', 6),
    ('6615', 'Indemnités de licenciement',                       'CHARGE', 6),
    ('6641', 'Cotisations INSS patronales',                      'CHARGE', 6),
    ('6642', 'Mutuelle de santé',                                'CHARGE', 6),
    ('6643', 'Assurance groupe accidents de travail',            'CHARGE', 6),
    ('6711', 'Intérêts des emprunts bancaires',                  'CHARGE', 6),
    ('6712', 'Intérêts sur découverts',                          'CHARGE', 6),
    ('6721', 'Pertes de change',                                 'CHARGE', 6),
    ('6731', 'Frais et commissions bancaires',                   'CHARGE', 6),
    ('6811', 'Dotations amortissements immobilisations incorporelles', 'CHARGE', 6),
    ('6812', 'Dotations amortissements immobilisations corporelles',   'CHARGE', 6),
    ('6911', 'Dotations provisions pour risques',                'CHARGE', 6),
    ('6912', 'Dotations dépréciations créances',                 'CHARGE', 6),

    -- ══════════════════════════════════════════════
    -- CLASSE 7 : Produits des activités ordinaires
    -- ══════════════════════════════════════════════
    ('7011', 'Ventes de marchandises — marché local',            'PRODUIT', 7),
    ('7012', 'Ventes de marchandises — exportation',             'PRODUIT', 7),
    ('7021', 'Ventes de produits finis',                         'PRODUIT', 7),
    ('7041', 'Travaux facturés',                                 'PRODUIT', 7),
    ('7051', 'Études et prestations de services',                'PRODUIT', 7),
    ('7052', 'Formations et séminaires facturés',                'PRODUIT', 7),
    ('7053', 'Commissions reçues',                               'PRODUIT', 7),
    ('7061', 'Services vendus',                                  'PRODUIT', 7),
    ('7071', 'Rabais, remises et ristournes accordés',           'PRODUIT', 7),
    ('7111', 'Subventions d''exploitation reçues',               'PRODUIT', 7),
    ('7112', 'Subventions d''équilibre',                         'PRODUIT', 7),
    ('7211', 'Immobilisations incorporelles produites',          'PRODUIT', 7),
    ('7212', 'Immobilisations corporelles produites',            'PRODUIT', 7),
    ('7511', 'Revenus locatifs',                                 'PRODUIT', 7),
    ('7512', 'Revenus de sous-traitance',                        'PRODUIT', 7),
    ('7521', 'Revenus de placements financiers',                 'PRODUIT', 7),
    ('7531', 'Récupérations sur créances amorties',              'PRODUIT', 7),
    ('7541', 'Dégrèvements et remboursements d''impôts',         'PRODUIT', 7),
    ('7591', 'Produits divers de gestion courante',              'PRODUIT', 7),
    ('7711', 'Dividendes reçus',                                 'PRODUIT', 7),
    ('7721', 'Intérêts sur comptes bancaires',                   'PRODUIT', 7),
    ('7722', 'Intérêts sur prêts accordés',                      'PRODUIT', 7),
    ('7731', 'Gains de change',                                  'PRODUIT', 7),
    ('7811', 'Transferts de charges d''exploitation',            'PRODUIT', 7),
    ('7911', 'Reprises sur dépréciations d''actif',              'PRODUIT', 7),
    ('7921', 'Reprises sur provisions pour risques',             'PRODUIT', 7),

    -- ══════════════════════════════════════════════
    -- CLASSE 8 : Hors activités ordinaires
    -- ══════════════════════════════════════════════
    ('8111', 'Valeurs comptables cessions immob. incorporelles', 'CHARGE',  8),
    ('8112', 'Valeurs comptables cessions immob. corporelles',   'CHARGE',  8),
    ('8211', 'Produits de cession immob. incorporelles',         'PRODUIT', 8),
    ('8212', 'Produits de cession immob. corporelles',           'PRODUIT', 8),
    ('8311', 'Charges exceptionnelles sur opérations de gestion','CHARGE',  8),
    ('8312', 'Charges exceptionnelles sur opérations en capital','CHARGE',  8),
    ('8411', 'Produits exceptionnels sur opérations de gestion', 'PRODUIT', 8),
    ('8412', 'Produits exceptionnels sur opérations en capital', 'PRODUIT', 8),
    ('8711', 'Participation des travailleurs aux bénéfices',     'CHARGE',  8),
    ('8911', 'Impôt sur les bénéfices des sociétés (IBS)',       'CHARGE',  8),
    ('8912', 'Impôt minimum forfaitaire (IMF)',                  'CHARGE',  8)

ON CONFLICT (numero) DO NOTHING;
